definitions:
  mapping.StructMapping:
    properties:
      data:
        items:
          $ref: '#/definitions/mapping.StructMappingItem'
        type: array
    type: object
  mapping.StructMappingItem:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  view.ReqCreateCrontab:
    properties:
      args:
        items:
          $ref: '#/definitions/view.ReqCrontabArg'
        type: array
      cron:
        type: string
      desc:
        type: string
      dutyUid:
        type: integer
      isRetry:
        type: integer
      retryInterval:
        type: integer
      retryTimes:
        type: integer
      typ:
        type: integer
    type: object
  view.ReqCrontabArg:
    properties:
      key:
        type: string
      val:
        type: string
    type: object
  view.ReqUpdateCrontab:
    properties:
      args:
        items:
          $ref: '#/definitions/view.ReqCrontabArg'
        type: array
      cron:
        type: string
      desc:
        type: string
      dutyUid:
        type: integer
      isRetry:
        type: integer
      retryInterval:
        type: integer
      retryTimes:
        type: integer
      typ:
        type: integer
    type: object
  view.RespDatabaseSimple:
    properties:
      cluster:
        type: string
      databaseName:
        type: string
      desc:
        type: string
      id:
        type: integer
      iid:
        type: integer
      isCreateByCV:
        type: integer
      tables:
        items:
          $ref: '#/definitions/view.RespTableSimple'
        type: array
    type: object
  view.RespInstanceSimple:
    properties:
      databases:
        items:
          $ref: '#/definitions/view.RespDatabaseSimple'
        type: array
      desc:
        type: string
      id:
        type: integer
      instanceName:
        type: string
    type: object
  view.RespNodeResult:
    properties:
      avatar:
        type: string
      content:
        type: string
      cost:
        type: integer
      ctime:
        type: integer
      email:
        type: string
      id:
        type: integer
      nickname:
        type: string
      nodeId:
        type: integer
      result:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
  view.RespNodeResultList:
    properties:
      list:
        items:
          $ref: '#/definitions/view.RespNodeResult'
        type: array
      total:
        type: integer
    type: object
  view.RespTableSimple:
    properties:
      createType:
        type: integer
      desc:
        type: string
      did:
        type: integer
      id:
        type: integer
      tableName:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Defines interface prefixes in terms of module overrides：
    - base : the global basic readable information module
    - storage : the log module
    - alarm : the alarm module
    - pandas : the data analysis module
    - cmdb : the configuration module
    - sysop : the system management module
  title: ClickVisual API
  version: 0.4.0
paths:
  /api/v2/base/instances:
    get:
      description: gets all instances, databases, and table nested data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.RespInstanceSimple'
            type: array
      summary: Gets all instance database and table data filtered by permissions
      tags:
      - base
  /api/v2/pandas/nodes-results/{result-id}:
    patch:
      consumes:
      - application/json
      description: only support excelProcess update
      parameters:
      - description: result id
        in: path
        name: result-id
        required: true
        type: integer
      - in: query
        name: excelProcess
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Updates the action on the execution result
      tags:
      - pandas
  /api/v2/pandas/nodes/:nodeId/crontab:
    patch:
      consumes:
      - application/json
      description: |-
        isRetry: 0 no 1 yes
        retryInterval: the unit is in seconds, 100 means 100s
      parameters:
      - description: node id
        in: path
        name: node-id
        required: true
        type: integer
      - description: params
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/view.ReqUpdateCrontab'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Updating a scheduled node scheduling task
      tags:
      - pandas
    post:
      consumes:
      - application/json
      description: |-
        isRetry: 0 no 1 yes
        retryInterval: the unit is in seconds, 100 means 100s
      parameters:
      - description: node id
        in: path
        name: node-id
        required: true
        type: integer
      - description: params
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/view.ReqCreateCrontab'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Creating a scheduled node scheduling task
      tags:
      - pandas
  /api/v2/pandas/nodes/:nodeId/lock-acquire:
    post:
      consumes:
      - application/json
      description: Force the file edit lock to be acquired
      parameters:
      - description: node id
        in: path
        name: node-id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Force the file edit lock to be acquired
      tags:
      - pandas
  /api/v2/pandas/nodes/{node-id}/results:
    get:
      consumes:
      - application/json
      description: Obtain the node execution result record
      parameters:
      - description: node id
        in: path
        name: node-id
        required: true
        type: integer
      - in: query
        name: current
        type: integer
      - in: query
        name: isExcludeCrontabResult
        type: integer
      - in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.RespNodeResultList'
      summary: Obtain the node execution result record
      tags:
      - pandas
  /api/v2/storage:
    post:
      consumes:
      - application/json
      description: Kafka JSON field mapping
      parameters:
      - in: query
        name: brokers
        required: true
        type: string
      - in: query
        name: consumers
        required: true
        type: integer
      - in: query
        name: databaseId
        type: integer
      - in: query
        name: days
        required: true
        type: integer
      - in: query
        name: desc
        type: string
      - in: query
        name: tableName
        required: true
        type: string
      - in: query
        name: topics
        required: true
        type: string
      - in: query
        name: typ
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Kafka JSON field mapping
      tags:
      - storage
  /api/v2/storage/mapping-json:
    post:
      consumes:
      - application/json
      description: Kafka JSON field mapping
      parameters:
      - in: query
        name: data
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mapping.StructMapping'
      summary: Kafka JSON field mapping
      tags:
      - storage
swagger: "2.0"
